project:
  type: website

website:
  title: "SCTO Statistics and Methodology platform tools and support"
  page-footer: CC-BY SCTO Statistics and Methodology platform
  navbar:
    background: primary
    left:
      - text: Home
        file: index.qmd
  sidebar:
    style: "floating"
    search: true
    align: left
    collapse-level: 1
    contents:
      - section: "For clinicians"
        contents:
          - SampleSizeCalculation.qmd
      - section: "For programmers"
        contents:
          - baselinetables.qmd
      - about.qmd
      - text: Blog
        file: blog/index.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
  bibliography: references.bib
  citations-hover: true

